{% set name = "django-redis" %}
{% set version = "5.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/django-redis-{{ version }}.tar.gz
  sha256: 6a02abaa34b0fea8bf9b707d2c363ab6adc7409950b2db93602e6cb292818c42

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - django >=2.2
    - redis-py >=3,!=4.0.0,!=4.0.1

test:
  imports:
    - django_redis
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/niwinz/django-redis
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Full featured redis cache backend for Django
  description: |
    django-redis is a BSD Licensed, full featured Redis cache/session backend for Django.
  doc_url: https://niwinz.github.io/django-redis/latest/
  dev_url: https://github.com/niwinz/django-redis

extra:
  recipe-maintainers:
    - cshaley
    - rxm7706
    - millsks
    - elanqo
    - zaigner
    - sannykr
