{% set name = "django-redis" %}
{% set version = "4.11.0" %}
{% set sha256 = "a5b1e3ffd3198735e6c529d9bdf38ca3fcb3155515249b98dc4d966b8ddf9d2b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - django >=1.8
    - redis-py

about:
  home: https://github.com/niwinz/django-redis
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Full featured redis cache backend for Django'
  description: |
    django-redis is a BSD Licensed, full featured Redis cache/session backend for Django.
  doc_url: https://niwinz.github.io/django-redis/latest/
  dev_url: https://github.com/niwinz/django-redis

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
