{% set name = "django-redis" %}
{% set version = "5.2.0" %}
{% set sha256 = "8a99e5582c79f894168f5865c52bd921213253b7fd64d16733ae4591564465de" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - django >=2.2
    - redis-py >=3,!=4.0.0,!=4.0.1

test:
  imports:
    - django_redis
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/niwinz/django-redis
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Full featured redis cache backend for Django
  description: |
    django-redis is a BSD Licensed, full featured Redis cache/session backend for Django.
  doc_url: https://niwinz.github.io/django-redis/latest/
  dev_url: https://github.com/niwinz/django-redis

extra:
  recipe-maintainers:
    - cshaley
    - rxm7706
    - millsks
    - elanqo
    - zaigner
    - sannykr
